services:
  docker-hub-proxy:
#    build: .
#    container_name: docker-hub-proxy
    image: qq510023514/docker-hub:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
